### ISSUE TITLE
Helper to create a Link header from a struct

### ISSUE THREAD

**Issue by xadhoom** [simonrand/ex_link_header#3]
What do you think about that ? Basically a simple helper to create links from a struct.

https://github.com/xadhoom/ex_link_header/pull/2/files

Note: just a sample PR to myself to show you the diff, if is ok I'll PR to you.

**Comment by simonrand** [comment]
Yeah I like the idea, but I think from an organisation point of view it might be time to split the parsing and creating into separate modules perhaps?

**Comment by xadhoom** [comment]
Well, yes it makes sense.
Also test can be splitted in a separate suite.

Any preference for the module names?
Do you want to keep the parse part as-is or rename it, too ?

Another idea I was thinking about it to put also parsed stuff into a struct, but this will completely break the API. Multiple links will be returned as a list of structs.

**Comment by xadhoom** [comment]
opened a PR
